name: Docker Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-and-push:
    runs-on: self-hosted

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Debug Dockerfile presence (helpful for debugging)
    - name: Debug Dockerfile presence
      run: |
        echo "Show location"
        pwd
    # Step 4: Restore
    - name: Restore dependencies
      run: dotnet restore ./Calculator/Calculator.sln

    # Step 5: Build the solution
    - name: Build solution
      run: dotnet build ./Calculator/Calculator.sln -c Release --no-restore

    # Step 6: Restore content
    - name: content restored
      run: |
        ls ./Calculator/Calculator.Test/

    # Step 7: Run unit tests
    - name: Run Unit Tests
      run: dotnet test ./Calculator/Calculator.Test/Calculator.Test.csproj -c Release --no-build --verbosity normal

    # Step 8: Build and Tag Docker Image
    - name: Build and Tag Docker Image
      run: |
        # Build the Docker image
        docker build \
          -f ./Calculator/Calculator/Dockerfile \
          -t "${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:${{ vars.IMAGE_TAG }}" .

    # Step 9: Run docker container
    - name: Run Docker Container
      run: |
        docker run -d \
          --name test-container \
          -p 8080:8080 \
          "${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:${{ vars.IMAGE_TAG }}"
    
    # Step 10: Wait for container
    - name: Wait for Container
      run: sleep 5

    # Step 11: Verify with curl
    - name: Verify Application
      run: |
        curl -f http://0.0.0.0:8080/health || (docker logs test-container && exit 1)
    
    # Step 12: Stop container
    - name: Stop and Remove Container
      run: |
        docker stop test-container

    # Step 13: Remove container 
    - name: Remove Container
      run: |
        docker rm test-container

    # Step 14: Push to Docker Hub
    - name: Push to Docker Hub
      run: |
        docker push "${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:${{ vars.IMAGE_TAG }}"